package com.epam.spring.homework3.exception;

public enum ErrorType {
    ENTITY_NOT_FOUND_ERROR_TYPE,
    ENTITY_CREATION_FAILED_ERROR_TYPE,
    ARGUMENT_NOT_VALID_ERROR_TYPE,
    FATAL_ERROR_TYPE,
    VALIDATION_ERROR_TYPE,
    SEAT_ALREADY_TAKEN_ERROR_TYPE,
    TOKEN_NOT_VALID_ERROR_TYPE
}
